In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
#데이터 path 불러오기
train = pd.read_csv('train/train.csv')
train_path= 'train/images/'

In [8]:
#총 이미지 데이터 18,900개에 맞게 늘리는 과정 + mask 착용여부 열에 추가
new_train = pd.DataFrame(index=range(0,18900), columns=['id', 'gender', 'race', 'age','mask', 'path'])
for index, data in train.iterrows():
    path = train.loc[index]['path']
    file_list = [f for f in os.listdir(train_path + path) if not f.startswith('.')]
    for i in range(7):
        new_train.loc[index*7 + i] = train.loc[index]
        new_train.loc[index*7 + i]['path'] = new_train.loc[index*7 + i]['path'] + '/' + file_list[i]
        if 'incorrect_mask' in file_list[i]:
            new_train.loc[index*7 + i]['mask'] = 'Incorrect'
        elif 'mask' in file_list[i]:
            new_train.loc[index*7 + i]['mask'] = 'mask'
        else:
            new_train.loc[index*7 + i]['mask'] = 'Not Wear'
new_train

,id,gender,race,age,mask,path
0,000001,female,Asian,45,Incorrect,000001_female_Asian_45/incorrect_mask.jpg
1,000001,female,Asian,45,mask,000001_female_Asian_45/mask1.jpg
2,000001,female,Asian,45,mask,000001_female_Asian_45/mask2.jpg
3,000001,female,Asian,45,mask,000001_female_Asian_45/mask3.jpg
4,000001,female,Asian,45,mask,000001_female_Asian_45/mask4.jpg
...,...,...,...,...,...,...
18895,006959,male,Asian,19,mask,006959_male_Asian_19/mask2.jpg
18896,006959,male,Asian,19,mask,006959_male_Asian_19/mask3.jpg
18897,006959,male,Asian,19,mask,006959_male_Asian_19/mask4.jpg
18898,006959,male,Asian,19,mask,006959_male_Asian_19/mask5.jpg
18899,006959,male,Asian,19,Not Wear,006959_male_Asian_19/normal.jpg

In [9]:
new_train.to_csv('new_train.csv')